# Generated by Django 5.1.1 on 2024-10-09 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="date",
            field=models.DateField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 10, 9, 2, 21, 31, 484744, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
