# Generated by Django 5.1.1 on 2024-10-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_remove_attendance_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="roll_number",
        ),
        migrations.AddField(
            model_name="user",
            name="ID_number",
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
